-- 1. Display employees with their department names
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       D.DEPARTMENT_NAME
FROM DL_EMPLOYEES E
INNER JOIN DL_DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- 2. Display employees with their job titles
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       J.JOB_TITLE,
       E.SALARY
FROM DL_EMPLOYEES E
INNER JOIN DL_JOBS J
    ON E.JOB_ID = J.JOB_ID;


-- 3. Display employees with department and location
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       D.DEPARTMENT_NAME,
       L.LOCATION_NAME,
       L.CITY
FROM DL_EMPLOYEES E
JOIN DL_DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN DL_LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;


-- 4. Display employee, manager, and department
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME AS EMPLOYEE_NAME,
       M.FIRST_NAME AS MANAGER_NAME,
       D.DEPARTMENT_NAME
FROM DL_EMPLOYEES E
LEFT JOIN DL_EMPLOYEES M
    ON E.MANAGER_ID = M.EMPLOYEE_ID
JOIN DL_DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- 5. Display all departments and their employees
SELECT D.DEPARTMENT_NAME,
       E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME
FROM DL_DEPARTMENTS D
LEFT JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME;


-- 6. Display employees and their performance ratings
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       P.PERFORMANCE_RATING,
       P.PERFORMANCE_SCORE
FROM DL_EMPLOYEES E
JOIN DL_PERFORMANCE P
    ON E.EMPLOYEE_ID = P.EMPLOYEE_ID;


-- 7. Display employees with salary history
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       S.OLD_SALARY,
       S.NEW_SALARY,
       S.EFFECTIVE_DATE
FROM DL_EMPLOYEES E
JOIN DL_SALARY_HISTORY S
    ON E.EMPLOYEE_ID = S.EMPLOYEE_ID;


-- 8. Display employees with attendance information
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       A.ATTENDANCE_DATE,
       A.STATUS,
       A.WORKING_HOURS
FROM DL_EMPLOYEES E
JOIN DL_ATTENDANCE A
    ON E.EMPLOYEE_ID = A.EMPLOYEE_ID;


-- 9. Display employees with their previous job history
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       J.JOB_TITLE,
       H.START_DATE,
       H.END_DATE
FROM DL_EMPLOYEES E
JOIN DL_JOB_HISTORY H
    ON E.EMPLOYEE_ID = H.EMPLOYEE_ID
JOIN DL_JOBS J
    ON H.JOB_ID = J.JOB_ID;


-- 10. Display department, employee, job, and salary
SELECT D.DEPARTMENT_NAME,
       E.FIRST_NAME,
       E.LAST_NAME,
       J.JOB_TITLE,
       E.SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
JOIN DL_JOBS J
    ON E.JOB_ID = J.JOB_ID
ORDER BY D.DEPARTMENT_NAME, E.SALARY DESC;
