-- 1. Display department-wise employee count
SELECT D.DEPARTMENT_NAME,
       COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM DL_DEPARTMENTS D
LEFT JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;


-- 2. Display department-wise total salary
SELECT D.DEPARTMENT_NAME,
       SUM(E.SALARY) AS TOTAL_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;


-- 3. Display department-wise average salary
SELECT D.DEPARTMENT_NAME,
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;


-- 4. Display minimum and maximum salary in each department
SELECT D.DEPARTMENT_NAME,
       MIN(E.SALARY) AS MIN_SALARY,
       MAX(E.SALARY) AS MAX_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;


-- 5. Display departments having more than 2 employees
SELECT D.DEPARTMENT_NAME,
       COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) > 2;


-- 6. Display departments having an average salary greater than 60000
SELECT D.DEPARTMENT_NAME,
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING AVG(E.SALARY) > 60000;


-- 7. Display departments where total salary exceeds 150000
SELECT D.DEPARTMENT_NAME,
       SUM(E.SALARY) AS TOTAL_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING SUM(E.SALARY) > 150000;


-- 8. Display job-wise employee count
SELECT J.JOB_TITLE,
       COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
FROM DL_JOBS J
LEFT JOIN DL_EMPLOYEES E
    ON J.JOB_ID = E.JOB_ID
GROUP BY J.JOB_TITLE;


-- 9. Display job-wise average salary
SELECT J.JOB_TITLE,
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
FROM DL_JOBS J
JOIN DL_EMPLOYEES E
    ON J.JOB_ID = E.JOB_ID
GROUP BY J.JOB_TITLE;


-- 10. Display departments with at least 2 employees
SELECT D.DEPARTMENT_NAME,
       COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
       SUM(E.SALARY) AS TOTAL_SALARY,
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
HAVING COUNT(E.EMPLOYEE_ID) >= 2
ORDER BY AVERAGE_SALARY DESC;
