-- 1. Categorize employees based on salary
SELECT EMPLOYEE_ID,
       FIRST_NAME,
       LAST_NAME,
       SALARY,
       CASE
           WHEN SALARY >= 80000 THEN 'HIGH'
           WHEN SALARY >= 60000 THEN 'MEDIUM'
           ELSE 'LOW'
       END AS SALARY_CATEGORY
FROM DL_EMPLOYEES;


-- 2. Categorize employees based on performance score
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       P.PERFORMANCE_SCORE,
       CASE
           WHEN P.PERFORMANCE_SCORE >= 85 THEN 'EXCELLENT'
           WHEN P.PERFORMANCE_SCORE >= 70 THEN 'GOOD'
           ELSE 'NEEDS IMPROVEMENT'
       END AS PERFORMANCE_CATEGORY
FROM DL_EMPLOYEES E
JOIN DL_PERFORMANCE P
    ON E.EMPLOYEE_ID = P.EMPLOYEE_ID;


-- 3. Calculate salary increase from salary history
SELECT EMPLOYEE_ID,
       OLD_SALARY,
       NEW_SALARY,
       NEW_SALARY - OLD_SALARY AS SALARY_INCREASE,
       ROUND(
           ((NEW_SALARY - OLD_SALARY) / OLD_SALARY) * 100,
           2
       ) AS INCREASE_PERCENTAGE
FROM DL_SALARY_HISTORY;


-- 4. Identify employees based on attendance status
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       A.STATUS,
       CASE
           WHEN A.STATUS = 'PRESENT' THEN 'Available'
           WHEN A.STATUS = 'LEAVE' THEN 'On Leave'
           ELSE 'Absent'
       END AS ATTENDANCE_CATEGORY
FROM DL_EMPLOYEES E
JOIN DL_ATTENDANCE A
    ON E.EMPLOYEE_ID = A.EMPLOYEE_ID;


-- 5. Department-wise salary category count
SELECT D.DEPARTMENT_NAME,
       COUNT(CASE
                 WHEN E.SALARY >= 80000 THEN 1
             END) AS HIGH_SALARY_EMPLOYEES,
       COUNT(CASE
                 WHEN E.SALARY BETWEEN 60000 AND 79999 THEN 1
             END) AS MEDIUM_SALARY_EMPLOYEES,
       COUNT(CASE
                 WHEN E.SALARY < 60000 THEN 1
             END) AS LOW_SALARY_EMPLOYEES
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME;


-- 6. Department-wise workforce salary report
SELECT D.DEPARTMENT_NAME,
       COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
       SUM(E.SALARY) AS TOTAL_SALARY,
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY,
       MIN(E.SALARY) AS MIN_SALARY,
       MAX(E.SALARY) AS MAX_SALARY
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY TOTAL_SALARY DESC;


-- 7. Employees with performance and salary information
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       E.SALARY,
       P.PERFORMANCE_SCORE,
       CASE
           WHEN P.PERFORMANCE_SCORE >= 85 AND E.SALARY >= 70000
               THEN 'HIGH PERFORMER'
           WHEN P.PERFORMANCE_SCORE >= 70
               THEN 'GOOD PERFORMER'
           ELSE 'REVIEW REQUIRED'
       END AS EMPLOYEE_CATEGORY
FROM DL_EMPLOYEES E
JOIN DL_PERFORMANCE P
    ON E.EMPLOYEE_ID = P.EMPLOYEE_ID;


-- 8. Attendance summary
SELECT A.STATUS,
       COUNT(*) AS TOTAL_RECORDS,
       ROUND(AVG(A.WORKING_HOURS), 2) AS AVERAGE_WORKING_HOURS
FROM DL_ATTENDANCE A
GROUP BY A.STATUS;


-- 9. Employees with salary above their job's maximum salary
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       J.JOB_TITLE,
       E.SALARY,
       J.MAX_SALARY
FROM DL_EMPLOYEES E
JOIN DL_JOBS J
    ON E.JOB_ID = J.JOB_ID
WHERE E.SALARY > J.MAX_SALARY;


-- 10. Employee reporting summary
SELECT D.DEPARTMENT_NAME,
       COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
       ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY,
       ROUND(AVG(P.PERFORMANCE_SCORE), 2) AS AVERAGE_PERFORMANCE
FROM DL_DEPARTMENTS D
JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
LEFT JOIN DL_PERFORMANCE P
    ON E.EMPLOYEE_ID = P.EMPLOYEE_ID
GROUP BY D.DEPARTMENT_NAME
ORDER BY AVERAGE_PERFORMANCE DESC;
