CREATE TABLE DL_LOCATIONS (
    LOCATION_ID NUMBER(5),
    LOCATION_NAME VARCHAR2(100),
    CITY VARCHAR2(50),
    STATE VARCHAR2(50),
    COUNTRY VARCHAR2(50)
);

CREATE TABLE DL_DEPARTMENTS (
    DEPARTMENT_ID NUMBER(5),
    DEPARTMENT_NAME VARCHAR2(100),
    LOCATION_ID NUMBER(5),
    MANAGER_ID NUMBER(5)
);

CREATE TABLE DL_JOBS (
    JOB_ID NUMBER(5),
    JOB_TITLE VARCHAR2(100),
    MIN_SALARY NUMBER(10,2),
    MAX_SALARY NUMBER(10,2)
);

CREATE TABLE DL_EMPLOYEES (
    EMPLOYEE_ID NUMBER(6),
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    EMAIL VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE,
    JOB_ID NUMBER(5),
    DEPARTMENT_ID NUMBER(5),
    MANAGER_ID NUMBER(6),
    SALARY NUMBER(10,2),
    COMMISSION_PCT NUMBER(5,2)
);

CREATE TABLE DL_JOB_HISTORY (
    JOB_HISTORY_ID NUMBER(8),
    EMPLOYEE_ID NUMBER(6),
    JOB_ID NUMBER(5),
    DEPARTMENT_ID NUMBER(5),
    START_DATE DATE,
    END_DATE DATE
);

CREATE TABLE DL_SALARY_HISTORY (
    SALARY_HISTORY_ID NUMBER(8),
    EMPLOYEE_ID NUMBER(6),
    OLD_SALARY NUMBER(10,2),
    NEW_SALARY NUMBER(10,2),
    EFFECTIVE_DATE DATE
);

CREATE TABLE DL_ATTENDANCE (
    ATTENDANCE_ID NUMBER(8),
    EMPLOYEE_ID NUMBER(6),
    ATTENDANCE_DATE DATE,
    STATUS VARCHAR2(20),
    WORKING_HOURS NUMBER(4,2)
);

CREATE TABLE DL_PERFORMANCE (
    PERFORMANCE_ID NUMBER(8),
    EMPLOYEE_ID NUMBER(6),
    REVIEW_DATE DATE,
    PERFORMANCE_RATING NUMBER(3,1),
    PERFORMANCE_SCORE NUMBER(5,2),
    COMMENTS VARCHAR2(500)
);
