ALTER TABLE DL_LOCATIONS
ADD CONSTRAINT PK_DL_LOCATIONS
PRIMARY KEY (LOCATION_ID);

ALTER TABLE DL_DEPARTMENTS
ADD CONSTRAINT PK_DL_DEPARTMENTS
PRIMARY KEY (DEPARTMENT_ID);

ALTER TABLE DL_JOBS
ADD CONSTRAINT PK_DL_JOBS
PRIMARY KEY (JOB_ID);

ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT PK_DL_EMPLOYEES
PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE DL_JOB_HISTORY
ADD CONSTRAINT PK_DL_JOB_HISTORY
PRIMARY KEY (JOB_HISTORY_ID);

ALTER TABLE DL_SALARY_HISTORY
ADD CONSTRAINT PK_DL_SALARY_HISTORY
PRIMARY KEY (SALARY_HISTORY_ID);

ALTER TABLE DL_ATTENDANCE
ADD CONSTRAINT PK_DL_ATTENDANCE
PRIMARY KEY (ATTENDANCE_ID);

ALTER TABLE DL_PERFORMANCE
ADD CONSTRAINT PK_DL_PERFORMANCE
PRIMARY KEY (PERFORMANCE_ID);


ALTER TABLE DL_LOCATIONS
ADD CONSTRAINT UQ_DL_LOCATION_NAME
UNIQUE (LOCATION_NAME);

ALTER TABLE DL_DEPARTMENTS
ADD CONSTRAINT UQ_DL_DEPARTMENT_NAME
UNIQUE (DEPARTMENT_NAME);

ALTER TABLE DL_JOBS
ADD CONSTRAINT UQ_DL_JOB_TITLE
UNIQUE (JOB_TITLE);

ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT UQ_DL_EMPLOYEE_EMAIL
UNIQUE (EMAIL);


ALTER TABLE DL_DEPARTMENTS
ADD CONSTRAINT FK_DL_DEPT_LOCATION
FOREIGN KEY (LOCATION_ID)
REFERENCES DL_LOCATIONS (LOCATION_ID);

ALTER TABLE DL_DEPARTMENTS
ADD CONSTRAINT FK_DL_DEPT_MANAGER
FOREIGN KEY (MANAGER_ID)
REFERENCES DL_EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT FK_DL_EMP_JOB
FOREIGN KEY (JOB_ID)
REFERENCES DL_JOBS (JOB_ID);

ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT FK_DL_EMP_DEPT
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DL_DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT FK_DL_EMP_MANAGER
FOREIGN KEY (MANAGER_ID)
REFERENCES DL_EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE DL_JOB_HISTORY
ADD CONSTRAINT FK_DL_HISTORY_EMP
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES DL_EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE DL_JOB_HISTORY
ADD CONSTRAINT FK_DL_HISTORY_JOB
FOREIGN KEY (JOB_ID)
REFERENCES DL_JOBS (JOB_ID);

ALTER TABLE DL_JOB_HISTORY
ADD CONSTRAINT FK_DL_HISTORY_DEPT
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES DL_DEPARTMENTS (DEPARTMENT_ID);

ALTER TABLE DL_SALARY_HISTORY
ADD CONSTRAINT FK_DL_SALARY_EMP
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES DL_EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE DL_ATTENDANCE
ADD CONSTRAINT FK_DL_ATTENDANCE_EMP
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES DL_EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE DL_PERFORMANCE
ADD CONSTRAINT FK_DL_PERFORMANCE_EMP
FOREIGN KEY (EMPLOYEE_ID)
REFERENCES DL_EMPLOYEES (EMPLOYEE_ID);


ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT CK_DL_EMP_SALARY
CHECK (SALARY > 0);

ALTER TABLE DL_EMPLOYEES
ADD CONSTRAINT CK_DL_EMP_COMMISSION
CHECK (COMMISSION_PCT IS NULL OR
       COMMISSION_PCT BETWEEN 0 AND 1);

ALTER TABLE DL_JOBS
ADD CONSTRAINT CK_DL_JOB_SALARY
CHECK (MIN_SALARY >= 0 AND MAX_SALARY >= MIN_SALARY);

ALTER TABLE DL_ATTENDANCE
ADD CONSTRAINT CK_DL_ATTENDANCE_STATUS
CHECK (STATUS IN ('PRESENT', 'ABSENT', 'LEAVE'));

ALTER TABLE DL_ATTENDANCE
ADD CONSTRAINT CK_DL_WORKING_HOURS
CHECK (WORKING_HOURS BETWEEN 0 AND 24);

ALTER TABLE DL_PERFORMANCE
ADD CONSTRAINT CK_DL_PERFORMANCE_RATING
CHECK (PERFORMANCE_RATING BETWEEN 1 AND 5);

ALTER TABLE DL_PERFORMANCE
ADD CONSTRAINT CK_DL_PERFORMANCE_SCORE
CHECK (PERFORMANCE_SCORE BETWEEN 0 AND 100);

ALTER TABLE DL_JOB_HISTORY
ADD CONSTRAINT CK_DL_HISTORY_DATES
CHECK (END_DATE >= START_DATE);

ALTER TABLE DL_SALARY_HISTORY
ADD CONSTRAINT CK_DL_SALARY_VALUES
CHECK (OLD_SALARY >= 0 AND NEW_SALARY >= 0);
