CREATE OR REPLACE VIEW DL_EMPLOYEE_DETAILS AS
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    E.EMAIL,
    E.HIRE_DATE,
    J.JOB_TITLE,
    D.DEPARTMENT_NAME,
    L.LOCATION_NAME,
    L.CITY,
    E.SALARY,
    E.COMMISSION_PCT
FROM DL_EMPLOYEES E
JOIN DL_JOBS J
    ON E.JOB_ID = J.JOB_ID
JOIN DL_DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN DL_LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;


CREATE OR REPLACE VIEW DL_DEPARTMENT_SALARY_REPORT AS
SELECT
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT,
    SUM(E.SALARY) AS TOTAL_SALARY,
    ROUND(AVG(E.SALARY), 2) AS AVERAGE_SALARY,
    MIN(E.SALARY) AS MIN_SALARY,
    MAX(E.SALARY) AS MAX_SALARY
FROM DL_DEPARTMENTS D
LEFT JOIN DL_EMPLOYEES E
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
GROUP BY
    D.DEPARTMENT_ID,
    D.DEPARTMENT_NAME;


CREATE OR REPLACE VIEW DL_EMPLOYEE_PERFORMANCE_REPORT AS
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    D.DEPARTMENT_NAME,
    P.REVIEW_DATE,
    P.PERFORMANCE_RATING,
    P.PERFORMANCE_SCORE,
    P.COMMENTS
FROM DL_EMPLOYEES E
JOIN DL_DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN DL_PERFORMANCE P
    ON E.EMPLOYEE_ID = P.EMPLOYEE_ID;


CREATE OR REPLACE VIEW DL_ATTENDANCE_REPORT AS
SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    D.DEPARTMENT_NAME,
    A.ATTENDANCE_DATE,
    A.STATUS,
    A.WORKING_HOURS
FROM DL_EMPLOYEES E
JOIN DL_DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN DL_ATTENDANCE A
    ON E.EMPLOYEE_ID = A.EMPLOYEE_ID;
